### ISSUE TITLE
CAN Message Update Frequency

### ISSUE THREAD

**Issue by RustyPedrosa** [spartanracingelectric/VCU#17]
Only send CAN messages if there has been an update or a certain amount of time has passed since the last message was sent.

Make this limitation easy to apply to all CAN messages.

(Use a universal CAN object for all messages?  Pass this CAN object through a CAN sending function that applies this limitation and tosses superfluous messages out while passing messages with new data to the FIFO queue?)

**Comment by GuySmily** [comment]
Develop an outgoing CAN handling system.  Whenever a system attempts to transmit a CAN message, it should:
- Keep a copy of the most recent previously sent message
- Keep track of when that previous message was sent
- When a new message is being sent, only transmit the message over CAN if...
  - Data has changed since the last message was sent
  - A certain time has elapsed since the last message was sent

Alternatively, develop a way to send messages only when needed (see subpoints above).
- Currently, this exists only for the motor control message
- A timestamp and data update counter was added to the motor controller object to support this
  - A decision must be made as to whether this is the best choice vs having a CAN handling system as above.

**Comment by GuySmily** [comment]
Alternatively, develop a way to send messages only when needed (see subpoints above).
- Currently, this exists only for the motor control message
- A timestamp and data update counter was added to the motor controller object to support this
  - A decision must be made as to whether this is the best choice vs having a CAN handling system as above.

**Comment by GuySmily** [comment]
```
CanManager* CanManager_new(canHandle0, canHandle1, defaultMinSendDelay, defaultMaxSendDelay);
//create can history data structure (AVL tree?)
//do other can init stuff


CanManager_setupMessage(ubyte2 messageID, ubyte4 timeBetweenMessages_Min, ubyte4 timeBetweenMessages_Max)
//add the parameters to can history datastructure


IO_ErrBlaBla CanManager_send(ubyte1 canHandle, IO_CAN_DATA_FRAME[] canMessages, ubyte? canMessageCount, bool force);
//Check if message data has changed
//Check if it's time to send message yet
  //If so, send message and update tree / linked list
//ToDo? write function to re-send message automatically if timebetweenMessages_Max has elapsed? (only applies to rinehart keepalive message)


//Helper functions
ubyte4 CanManager_timeSinceLastTransmit(IO_CAN_DATA_FRAME* canMessage)  //Overflows/resets at 74 min
bool CanManager_enoughTimeSinceLastTransmit(IO_CAN_DATA_FRAME* canMessage) // timesincelast > timeBetweenMessages_Min
bool CanManager_dataChangedSinceLastTransmit(IO_CAN_DATA_FRAME* canMessage) //bitwise comparison for all data bytes

//Keep track of CAN message IDs, their data, and when they were last sent.
typedef struct canMessageControls
{
  ubyte2 canMessageID;
  ubyte4 timeBetweenMessages_Min;
  ubyte4 timeBetweenMessages_Max;
  ubyte1 lastMessage_data[8];
  ubyte4 lastMessage_timeStamp;
  canHistoryNode* left;
  canHistoryNode* right;
}
```

**Comment by GuySmily** [comment]
CanManager sends messages without delaying in case of repeat / too soon
